// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      clean: ["dist", "build"],
      jade: {
        compile: {
          options: {
            data: {
              debug: false
            }
          },
          files: {
            "dist/index.html": "src/jade/index.jade",
            "dist/4xx.html": "src/jade/4xx.jade",
            "dist/company/index.html": "src/jade/company/about-us.jade",
            "dist/company/careers/index.html": "src/jade/company/careers.jade",
            "dist/company/leadership/index.html": "src/jade/company/leadership.jade",
            "dist/company/press/index.html": "src/jade/company/press.jade",
            "dist/company/resources/index.html": "src/jade/resources.jade",
            "dist/customers/index.html": "src/jade/customers.jade",
            "dist/privacy-policy/index.html": "src/jade/company/privacy-policy.jade",
            "dist/product/index.html": "src/jade/product.jade",
            "dist/terms-of-service/index.html": "src/jade/company/tos.jade",
            "dist/tour/api/index.html": "src/jade/tour/api.jade",
            "dist/tour/chrome/index.html": "src/jade/tour/chrome.jade",
            "dist/tour/salesforce/index.html": "src/jade/tour/salesforce.jade",
            "dist/tour/slack/index.html": "src/jade/tour/slack.jade",
            "dist/tour/marketo/index.html": "src/jade/tour/marketo.jade",
            "dist/who-benefits/index.html": "src/jade/who-benefits.jade"
          }
        }
      },
      less: {
        main: {
          files: {
            "dist/css/style.css": "src/less/main.less"
          }
        }
      },
      uglify: {
        main: {
          files: {
            'build/js/main.js': 'src/js/main.js'
          }
        }
      },
      copy: {
        "static": {
          expand: true,
          cwd: "src/static/",
          src: "**",
          dest: "dist/"
        },
        img: {
          expand: true,
          cwd: "src/img/",
          src: "**",
          dest: "dist/img/"
        },
        favicon: {
          expand: true,
          cwd: "src/img/",
          src: "favicon.ico",
          dest: "dist/"
        },
        js: {
          expand: true,
          cwd: "build/js/",
          src: "**",
          dest: "dist/js/"
        },
        fonts: {
          files: [
            {
              expand: true,
              cwd: 'node_modules/marble/vendor/font-awesome4/fonts/',
              src: ['*'],
              dest: 'dist/fonts/'
            }, {
              expand: true,
              cwd: 'node_modules/marble/icomoon/fonts/',
              src: ['*'],
              dest: 'dist/fonts/'
            }
          ]
        },
        foxhound: {
          expand: true,
          cwd: '../foxhound/scripts/',
          src: ['fxhnd.js'],
          dest: 'dist/js/'
        }
      },
      connect: {
        server: {
          options: {
            livereload: 9004,
            port: 8000,
            base: "dist"
          }
        }
      },
      watch: {
        options: {
          livereload: 9004
        },
        jade: {
          files: ['src/jade/**/*.jade'],
          tasks: ['jade']
        },
        less: {
          files: ['src/less/**/*.less'],
          tasks: ['less']
        },
        img: {
          files: ['src/img/**'],
          tasks: ['copy:img']
        },
        favicon: {
          files: ['src/img/favicon.ico'],
          tasks: ['copy:favicon']
        },
        js: {
          files: ['src/js/**'],
          tasks: ['uglify', 'copy:js']
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-clean");
    grunt.loadNpmTasks("grunt-contrib-connect");
    grunt.loadNpmTasks("grunt-contrib-copy");
    grunt.loadNpmTasks("grunt-contrib-jade");
    grunt.loadNpmTasks("grunt-contrib-less");
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    return grunt.registerTask('default', ["clean", "jade", "less", "uglify", "copy", "connect:server", "watch"]);
  };

}).call(this);
